kube_state_metrics:
  enabled: true
  image: quay.io/coreos/kube-state-metrics:v1.9.5
defaultRules:
  create: false
alertmanager:
  enabled: false
grafana:
  enabled: false     
nodeExporter:
  enabled: true
  image: prom/node-exporter:v0.18.1

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 2      
    retention: 12h   # we only need a few hours of retention, since the rest is uploaded to s3 
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    thanos:         # add Thanos Sidecar        
      image: quay.io/thanos/thanos:v0.12.1
      objectStorageConfig:
        name: thanos-storage-config
        key: thanos-storage-config.yaml
  image: prom/prometheus:v2.14.0
  clusterName: my-prometheus
  replicas: 2
  storage: 20Gi
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

thanosService:
  enabled: false
  annotations: {}
  labels: {}
  portName: grpc
  port: 10901
  targetPort: "grpc"
thanos:
  image: quay.io/thanos/thanos:v0.12.1
  query:
    enabled: true
    replicas: 2
    # Other Query or Store Endpoints which need to be stacked should be specified here.
    extraArgs: {}
    #  store: <IP>:<PORT>
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    service:
      type: ClusterIP
    scrape:
      enabled: false
      type: LoadBalancer
      annotations:
        cloud.google.com/load-balancer-type: Internal
  compactor:
    enabled: true
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

  store:
    enabled: true
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 0.5
        memory: 1Gi

  ruler:
    enabled: true
    replicas: 1
    rules_bucket: prometheus-rules-archive
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 100Mi

thanosIngress:
  enabled: false
ingress:
  enabled: false
