apiVersion: v2
name: kubernetes-external-secrets
version: 8.1.3
appVersion: 8.1.3
description: Kubernetes External Secrets CustomResourceDefinition
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/kubernetes-external-secrets
sources:
  - https://github.com/external-secrets/kubernetes-external-secrets
maintainers:
  - name: external-secrets
    url: https://github.com/external-secrets
